### ISSUE TITLE
specify output folder as system property?

### ISSUE THREAD

**Issue by HesterLyons** [prashant-ramcharan/courgette-jvm-selenium#1]
Hi, 

I've been wondering if it is possible to specify the output folder as a system property and use this in the Courgette options at all? That way there could be a single test suite that could be called with command line arguments to direct it to different browsers, and write the outputs to the correct folder - unless it is not possible to use system properties in the courgette options? I did try to get this to work but I'm not sure I'm going the right way about it.

**Comment by prashant-ramcharan** [comment]
Hello,

Which output folder are you referring to? Is it the report output?

You can use system properties to override all Courgette Options at runtime. https://github.com/prashant-ramcharan/courgette-jvm#gradle-run-options

**Comment by HesterLyons** [comment]
Hi, yes it was the report output. Thanks for the response. So, if I specify -Dcourgette.reportTargetDir="C:\myFolder" this would override? In that case I think you've solved all my problems!

**Comment by prashant-ramcharan** [comment]
Yes, that's correct - the reportTargetDir would be overridden.

**Comment by HesterLyons** [comment]
This works an absolute treat. Thank you.
