### ISSUE TITLE
Parallel functionality not working for feature run level with no rerun on fail

### ISSUE THREAD

**Issue by rick-james-norwex** [prashant-ramcharan/courgette-jvm-selenium#3]
Hello, we are looking for a parallel solution for our project and ran across courgette. We added into our project following the examples provided but the tests are still running in sequence not in parallel. The selenium code runs as we are seeing scenarios output in both the courgette report and the cucumber html report. However each scenario runs back to back and at the end only a single cucumber.json file is generated instead of one json per thread. We're not passing any overrride values in the console, just running with ./gradlew smokeSuite

Are we missing something perhaps?

For the attachment extensions, I had to make them all .txt only because github does not support extensions for .gradle or .java only the project folder structure is really a .txt file

[project folder structure.txt](https://github.com/prashant-ramcharan/courgette-jvm-selenium/files/3865873/project.folder.structure.txt)
[build.gradle.txt](https://github.com/prashant-ramcharan/courgette-jvm-selenium/files/3865874/build.gradle.txt)
[SmokeTestSuite.txt](https://github.com/prashant-ramcharan/courgette-jvm-selenium/files/3865877/SmokeTestSuite.txt)
[hooks.txt](https://github.com/prashant-ramcharan/courgette-jvm-selenium/files/3865879/hooks.txt)

**Comment by prashant-ramcharan** [comment]
Hello, 

`CourgetteRunLevel.FEATURE` only runs feature files in parallel (_scenarios within the feature files are executed sequentially_)

`CourgetteRunLevel.SCENARIO` runs all scenarios in parallel.

Looking at your project folder structure I can see that you have 1 feature file `someTest.feature` 

If you using `CourgetteRunLevel.FEATURE` then scenarios within this feature file will execute sequentially. 

For example:

_Runner_
````java
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 5
        // ...
)
````

_Project structure_
````
feature_a (has 2 scenarios)
feature_b (has 3 scenarios)
````
If you run the above using feature level, then **both features** would run in parallel but the scenarios within each feature file will run in sequence. 

If you run the above using scenario level, then **all 5 scenarios** would run in parallel at the same time.

**Comment by rick-james-norwex** [comment]
Hello,

Thanks very much for the input, tests are running now with expected behavior after adding additional features.

Best regards,
Courgette user
