### ISSUE TITLE
Error: Could not find or load main class io.cucumber.core.cli.Main

### ISSUE THREAD

**Issue by sharti** [prashant-ramcharan/courgette-jvm-selenium#7]
Hi Prashant,

I have been using latest version of cougrette that is 5.9.2 with Junit 4.13.1 along with Junit Jupiter and vintage version 5.7.0
Unfortunately, my cucumber tests are not being triggered it just throws 
Error: Could not find or load main class io.cucumber.core.cli.Main
Caused by: java.lang.ClassNotFoundException: io.cucumber.core.cli.Main
Along with :
There were errors when running the test. Refer to the console for more information.
courgette.runtime.CourgetteTestErrorException: There were errors when running the test. Refer to the console for more information.
below is my testRunner:
@RunWith(Courgette.class)
@CourgetteOptions(

    threads = 1,
    runLevel = CourgetteRunLevel.SCENARIO,
    rerunFailedScenarios = true,
    rerunAttempts = 3,
    showTestOutput = true,
    reportTargetDir = "build",
    classPath = {"build/libs/*", "build/classes/java/test"},
    cucumberOptions = @CucumberOptions(
        features = "fne/lls/src/test/resources/com/flexnetls/automation/",
        glue={"com.flexnetls.automation.stepdefs"},
        plugin = {
            "pretty",
            "json:build/cucumber-report/cucumber.json",
            "html:build/cucumber-report/cucumber.html",
            "junit:build/cucumber-report/cucumber.xml"

        },
        monochrome = true
    )
)
public class CucumberTestRunner {
  @CourgetteBeforeAll
  public static void setup() {
    System.out.println("before all");
  }
}
gradle dependencies, test and cucumber tasks are as below:
dependencies {

    compile group: 'org.aspectj', name: 'aspectjweaver', version: '1.9.4'
    compile group: 'io.github.prashant-ramcharan', name: 'courgette-jvm', version: '5.9.2'
    testRuntime group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.7.0'
   testRuntime group: 'org.junit.vintage', name: 'junit-vintage-engine', version: '5.7.0'
    testImplementation group: 'junit', name: 'junit', version: '4.13.1'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.7.0'
   testImplementation group: 'io.cucumber', name: 'cucumber-java8', version: '6.9.1'
    testImplementation group: 'io.cucumber', name: 'cucumber-junit', version: '6.9.1'
}
test {
    dependsOn copyLibs
    doFirst {
//        def cp =  CollectionUtils.join(File.pathSeparator, classpath.getFiles())
//        environment 'CLASSPATH', cp
//        classpath = classpath.filter { false }
        def weaver = configurations.compile.find { it.name.contains("aspectjweaver") }
        systemProperties System.getProperties()
        scanForTestClasses = false
        if (System.getProperty('DEBUG', 'false') == 'true') {
            jvmArgs '-Xdebug',
                    '-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=*:9009'

            jvmArgs = jvmArgs << "-javaagent:${weaver}"
        } else {
            jvmArgs = jvmArgs << "-javaagent:${weaver}"
        }
    }
    useJUnitPlatform()
    testLogging {
        events "PASSED", "SKIPPED", "FAILED"
    }
    testLogging.showStandardStreams = true
    testLogging.exceptionFormat = 'full'

    reports {
        junitXml.enabled = true
        html.enabled = true
    }

    afterSuite { desc, result ->
        result.exception?.printStackTrace()
        if (!desc.parent) {
            println "\nJunit Test result: ${result.resultType}"
            println "Junit Test summary: ${result.testCount} tests, " +
                    "${result.successfulTestCount} succeeded, " +
                    "${result.failedTestCount} failed, " +
                    "${result.skippedTestCount} skipped"
        }
    }
    //exclude("**/*")
}
task cucumber {
    dependsOn assemble, compileTestJava
    doLast {
        javaexec {
            main = "io.cucumber.core.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = ['--plugin', 'pretty', '--glue', 'com.flexnetls.automation.stepdefs', 'src/test/resources/com/flexnetls/automation']
        }
    }

}

Any help is highly appreciated.

**Comment by prashant-ramcharan** [comment]
Refer to https://github.com/prashant-ramcharan/courgette-jvm/issues/256
